namespace: monitoring

controller:
  kind: Deployment
  replicaCount: 1

  resources:
    limits:
      cpu: 100m
      memory: 90Mi
    requests:
      cpu: 100m
      memory: 90Mi

  service:
    annotations: {}